// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvhjicczwktvdscokymc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2aGppY2N6d2t0dmRzY29reW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5Mzc0OTIsImV4cCI6MjA1MjUxMzQ5Mn0.V3x8TErQyD83Vl3i17UipajvtC_PpcPVWMBAZpu9pn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);